# Generated by Django 4.0.6 on 2022-07-15 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Django', '0002_service1_service2_service3'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service2',
        ),
        migrations.DeleteModel(
            name='Service3',
        ),
        migrations.AddField(
            model_name='services',
            name='content1',
            field=models.TextField(default='SOME STRING', max_length=512),
        ),
        migrations.AddField(
            model_name='services',
            name='content2',
            field=models.TextField(default='SOME STRING', max_length=512),
        ),
        migrations.AddField(
            model_name='services',
            name='content3',
            field=models.TextField(default='SOME STRING', max_length=512),
        ),
    ]
