# Generated by Django 4.0.6 on 2022-07-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Django', '0003_delete_service2_delete_service3_services_content1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content1', models.TextField(default='SOME STRING', max_length=512)),
                ('content2', models.TextField(default='SOME STRING', max_length=512)),
                ('content3', models.TextField(default='SOME STRING', max_length=512)),
            ],
        ),
        migrations.DeleteModel(
            name='Service1',
        ),
        migrations.RemoveField(
            model_name='services',
            name='content1',
        ),
        migrations.RemoveField(
            model_name='services',
            name='content2',
        ),
        migrations.RemoveField(
            model_name='services',
            name='content3',
        ),
    ]
