# Generated by Django 4.0.6 on 2022-07-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Django', '0004_service_delete_service1_remove_services_content1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticlesChauds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('Article_Img', models.ImageField(upload_to='../../frontend/assets/')),
            ],
        ),
    ]
