# Generated by Django 4.0.6 on 2022-07-18 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Django', '0005_articleschauds'),
    ]

    operations = [
        migrations.RenameField(
            model_name='articleschauds',
            old_name='Article_Img',
            new_name='article_img',
        ),
    ]
