# Generated by Django 4.0.6 on 2022-07-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Django', '0007_alter_articleschauds_article_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='articleschauds',
            name='price',
            field=models.SmallIntegerField(default='0'),
        ),
    ]
