# Generated by Django 4.0.6 on 2022-07-19 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Django', '0008_articleschauds_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articleschauds',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=1000),
        ),
    ]
